# Generated by Django 4.2.8 on 2023-12-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-created_at',), 'verbose_name': 'نمایش محصولات', 'verbose_name_plural': 'نمایش محصولات'},
        ),
    ]
