# Generated by Django 4.2.8 on 2024-01-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbarpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='evidence',
            field=models.ImageField(default=2, upload_to='team/evidence/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourteam',
            name='gmail',
            field=models.EmailField(default=1, max_length=254, verbose_name='ایمیل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourteam',
            name='work_about',
            field=models.TextField(default=1, verbose_name='درباره مدرک یا کار های که کردین'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourteam',
            name='your_about',
            field=models.TextField(default=1, verbose_name='درباره خود'),
            preserve_default=False,
        ),
    ]
