# Generated by Django 4.2.8 on 2023-12-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbarpage', '0002_aboutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'شرکای ما',
                'verbose_name_plural': 'شرکای ما',
            },
        ),
        migrations.CreateModel(
            name='OurStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='about/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'داستان ما',
                'verbose_name_plural': 'داستان ما',
            },
        ),
    ]
