# Generated by Django 4.2.8 on 2023-12-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbarpage', '0003_ourpartners_ourstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('silence', models.CharField(max_length=70, verbose_name='صمت فرد')),
                ('image', models.ImageField(upload_to=None)),
                ('instagram', models.CharField(max_length=256, verbose_name='لینک اینستاگرام')),
                ('telegram', models.CharField(max_length=256, verbose_name='لینک تلگرام')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تیم ما',
                'verbose_name_plural': 'تیم ما',
            },
        ),
    ]
