# Generated by Django 4.2.8 on 2024-01-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbarpage', '0003_alter_ourteam_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='evidence_three',
            field=models.ImageField(blank=True, null=True, upload_to='team/evidence2/', verbose_name='3عکس مدرک'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='evidence_two',
            field=models.ImageField(blank=True, null=True, upload_to='team/evidence1/', verbose_name='2عکس مدرک'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='team/evidence/', verbose_name='عکس مدرک'),
        ),
    ]
