# Generated by Django 4.2.8 on 2023-12-12 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbarpage', '0006_sharemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareModel',
        ),
    ]
