# Generated by Django 4.2.7 on 2023-11-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(default=1, max_length=250, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
