# Generated by Django 4.2.7 on 2023-12-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['user'], 'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ ها'},
        ),
    ]
