# Generated by Django 4.2.7 on 2023-12-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ ها'},
        ),
    ]
