# Generated by Django 4.2.8 on 2024-01-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=70, verbose_name='نام')),
                ('title', models.CharField(max_length=70, verbose_name='نام دوم')),
                ('Description', models.TextField(verbose_name='توضیحات')),
                ('img', models.ImageField(upload_to='image/background', verbose_name='عکس')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
            },
        ),
        migrations.CreateModel(
            name='MenuFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('img', models.ImageField(upload_to='image/food', verbose_name='عکس محصول')),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محصولات جدید',
                'verbose_name_plural': 'محصولات جدید',
            },
        ),
        migrations.CreateModel(
            name='MenuProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='نام محصول')),
                ('img', models.ImageField(upload_to='image/product', verbose_name='عکس محصول')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'منوی محصولات',
                'verbose_name_plural': 'منوی محصولات ها',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='تلگرام')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام')),
            ],
            options={
                'verbose_name': 'شبکه های اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='نام')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('discount', models.IntegerField(verbose_name='قیمت تخفیف')),
                ('Description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'پیشنهاد ویژه',
                'verbose_name_plural': 'پیشنهاد ویژه',
            },
        ),
    ]
