# Generated by Django 4.2.7 on 2023-11-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=70, verbose_name='نام')),
                ('title', models.CharField(max_length=70, verbose_name='نام دوم')),
                ('Description', models.TextField(verbose_name='توضیحات')),
                ('img', models.ImageField(upload_to='image/background', verbose_name='عکس')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
            },
        ),
    ]
