# Generated by Django 4.2.7 on 2023-11-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_menuproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='نام')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('discount', models.IntegerField(verbose_name='قیمت تخفیف')),
                ('Description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'پیشنهاد ویژه',
                'verbose_name_plural': 'پیشنهاد ویژه',
            },
        ),
    ]
